"""создал директорию models

Revision ID: 7b0b1abfaa6d
Revises: 6f2bb977c7b2
Create Date: 2025-08-17 12:49:01.633435

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7b0b1abfaa6d'
down_revision: Union[str, Sequence[str], None] = '6f2bb977c7b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
