"""false

Revision ID: 7e2ecc759831
Revises: 7b0b1abfaa6d
Create Date: 2025-08-21 19:53:28.188169

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7e2ecc759831'
down_revision: Union[str, Sequence[str], None] = '7b0b1abfaa6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('todo_items_title_key'), 'todo_items', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('todo_items_title_key'), 'todo_items', ['title'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
